export const STRIPE_BASE_URL = "http://localhost:1337";
export const FETCH_HEADER_DATA = "http://localhost:1337/api/home-static?populate=*"
export const EVENTS_URL = "http://localhost:1337/api/events";
export const IMG_URL = "http://localhost:1337/api/images";
export const FETCH_FOOTER_DATA = "http://localhost:1337/api/footer-detail?populate=*"
export const LEFT_ARROW_IMG = "http://localhost:1337/uploads/left_arrow_2bbb40d1f3.png";
export const RIGHT_ARROW_IMG = "http://localhost:1337/uploads/right_arrow_29654e4b42.png";
export const CLOSE_BTN_IMG = "http://localhost:1337/uploads/close_Btn_083f19529c.png";
export const CAL_ICON = "http://localhost:1337/uploads/cal_a0fd1395bc.png"